#ifndef COSC_ASSIGN_TWO_TYPES
#define COSC_ASSIGN_TWO_TYPES

#include <math.h>

#define BOARD_ROW 82
#define BOARD_COL 28
#define NODE_LIST_MAX_SIZE 6
#define MAX_NUMBER_OF_LINKED_LIST 52
#define ASCII_DIFFERENCE 63
#define TILE_SET_NUM 2
#define TOTAL_COLOUR_NUM 6
#define TOTAL_SHAPE_NUM 6

#endif // COSC_ASSIGN_TWO_TYPES