#ifndef COSC_ASSIGN_TWO_TYPES
#define COSC_ASSIGN_TWO_TYPES

#include <math.h>

#define BOARD_SIZE 26
#define MAX_POS_SIZE 26*26
#define NODE_LIST_MAX_SIZE 6
#define MAX_NUMBER_OF_LINKED_LIST 52
#define ASCII_DIF 17
#define EACH_TILE_NUM 2
#define TOTAL_COLOUR_NUM 6
#define TOTAL_SHAPE_NUM 6
#define SPACE_FOR_ONE_TILE 3
#define TILES_IN_HAND_NUM 6
#define TOTAL_TILES_NUM 72
#define ROUND_NUM 30
#define EMPTY_TILE_BAG_ROUND_NUM 5
#define ASCII_A 65
#define ASCII_0 48

#endif // COSC_ASSIGN_TWO_TYPES